- columns:
  - column_name: timestamp
    expression: ''
    is_dttm: true
    type: TIMESTAMP WITH TIME ZONE
  - column_name: destination_app
    expression: ''
    type: VARCHAR
  - column_name: source_app
    expression: ''
    type: VARCHAR
  - column_name: protocol
    expression: ''
    type: VARCHAR
  - column_name: bytes
    expression: ''
    type: DOUBLE
  metrics:
  - expression: count(*)
    extra: '{"warning_markdown":null}'
    metric_name: count
  schema: default
  sql: "select\n\t\"timestamp\",\n\tvalue as bytes,\n\telement_at(labels,\n\t'source_workload')\
    \ as source_app,\n\telement_at(labels,\n\t'destination_workload') as destination_app,\n\
    \telement_at(labels,\n\t'request_protocol')  as protocol\nfrom\n\tprometheus.\"\
    default\".istio_request_bytes_sum \n\t\nwhere element_at(labels,'destination_workload')\
    \ not in ('unknown') and element_at(labels,'source_workload') not in ('unknown')\n"
  table_name: K8S Istio Traffic
